#ifndef ALGORITHMICCHALLENGES_3_DELETEMIDDLENODE_H
#define ALGORITHMICCHALLENGES_3_DELETEMIDDLENODE_H

class ListNode;

void deleteNode(ListNode* toDelete);

#endif //ALGORITHMICCHALLENGES_3_DELETEMIDDLENODE_H
