#ifndef ALGORITHMICCHALLENGES_4_CHECKBALANCED_H
#define ALGORITHMICCHALLENGES_4_CHECKBALANCED_H

#include "DataStructures/BST.h"

bool checkBalanced(const Bst& bst);

#endif //ALGORITHMICCHALLENGES_4_CHECKBALANCED_H
