cc_test(
  name = "RangeSumQueryMutableTest",
  size = "small",
  srcs = [
      "307_RangeSumQueryMutable.h",
      "307_RangeSumQueryMutableTest.cpp",
  ],
  deps = ["@com_google_googletest//:gtest_main"],
)
